name: Deploy to FTP

on: [push]

jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.abelmasov.ru
          username: mm
          password: v13o7#5Iu
          protocol: ftps
