name: Deploy to FTP

on: [push]

jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: abelmasov.ru
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/php/**
