name: Deploy to FTP

on: [push]

jobs:
  ftp-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: abelmasov.ru
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/php/**
